version: '3.8'
services:
  postgres:
    container_name: besui_postgres
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-besui}
    ports:
      - '5434:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
