[package]
name = "besui-config"
version = "0.1.0"
edition = "2021"
license-file = "../../LICENSE"

[dependencies]
dotenvy = "0.15.6"
config = "0.13.2"
anyhow = "1.0.61"
tracing = "0.1.37"
serde = "1.0.144"
# lazy_static = "1.4.0"
once_cell = "1.16.0"