//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "token")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub symbol: String,
    pub name: String,
    pub updated_at: DateTime,
    pub exchanges: Option<String>,
    pub image: Option<String>,
    pub circulating_supply: Option<i64>,
    pub total_supply: Option<i64>,
    pub max_supply: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
